// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DigitalTwin.WebAPI.Data;

#nullable disable

namespace DigitalTwin.WebAPI.Migrations
{
    [DbContext(typeof(WorkOrderServiceDbContext))]
    [Migration("20260820124351_AddedWorkOrderHistory")]
    partial class AddedWorkOrderHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderService.Models.ExternalSystem", b =>
                {
                    b.Property<string>("ExternalSystemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalSystemCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ExternalSystemDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExternalSystemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("ExternalSystemId");

                    b.ToTable("ExternalSystems");
                });

            modelBuilder.Entity("WorkOrderService.Models.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrders.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalSystemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkOrderDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WorkOrderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkOrderStatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("ExternalSystemId");

                    b.HasIndex("SiteId");

                    b.HasIndex("WorkOrderStatusId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrders.WorkOrderHistory", b =>
                {
                    b.Property<string>("WorkOrderHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderStatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WorkOrderHistoryId");

                    b.HasIndex("WorkOrderStatusId");

                    b.ToTable("WorkOrderHistories");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrders.WorkOrderStatus", b =>
                {
                    b.Property<string>("WorkOrderStatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("WorkOrderStatusId");

                    b.ToTable("WorkOrderStatuses");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrders.WorkOrder", b =>
                {
                    b.HasOne("WorkOrderService.Models.ExternalSystem", "ExternalSystem")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ExternalSystemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WorkOrderService.Models.Site", "Site")
                        .WithMany("WorkOrders")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkOrderService.Models.WorkOrders.WorkOrderStatus", "WorkOrderStatus")
                        .WithMany("WorkOrders")
                        .HasForeignKey("WorkOrderStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExternalSystem");

                    b.Navigation("Site");

                    b.Navigation("WorkOrderStatus");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrders.WorkOrderHistory", b =>
                {
                    b.HasOne("WorkOrderService.Models.WorkOrders.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderHistories")
                        .HasForeignKey("WorkOrderHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderService.Models.WorkOrders.WorkOrderStatus", "WorkOrderStatus")
                        .WithMany("WorkOrderHistories")
                        .HasForeignKey("WorkOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkOrderStatus");
                });

            modelBuilder.Entity("WorkOrderService.Models.ExternalSystem", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("WorkOrderService.Models.Site", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrders.WorkOrder", b =>
                {
                    b.Navigation("WorkOrderHistories");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrders.WorkOrderStatus", b =>
                {
                    b.Navigation("WorkOrderHistories");

                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
