// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DigitalTwin.WebAPI.Data;

#nullable disable

namespace DigitalTwin.WebAPI.Migrations
{
    [DbContext(typeof(WorkOrderServiceDbContext))]
    [Migration("20260819133828_AddModels")]
    partial class AddModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderService.Models.SiteCode", b =>
                {
                    b.Property<string>("SiteCodeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SiteDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SiteCodeId");

                    b.ToTable("SiteCodes");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteCodeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkOrderDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WorkOrderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkOrderStatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("SiteCodeId");

                    b.HasIndex("WorkOrderStatusId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrderHistory", b =>
                {
                    b.Property<string>("WorkOrderHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WorkOrderHistoryId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderHistories");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrderStatus", b =>
                {
                    b.Property<string>("WorkOrderStatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("WorkOrderStatusId");

                    b.ToTable("WorkOrderStatuses");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrder", b =>
                {
                    b.HasOne("WorkOrderService.Models.SiteCode", "SiteCode")
                        .WithMany()
                        .HasForeignKey("SiteCodeId");

                    b.HasOne("WorkOrderService.Models.WorkOrderStatus", "WorkOrderStatus")
                        .WithMany()
                        .HasForeignKey("WorkOrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteCode");

                    b.Navigation("WorkOrderStatus");
                });

            modelBuilder.Entity("WorkOrderService.Models.WorkOrderHistory", b =>
                {
                    b.HasOne("WorkOrderService.Models.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });
        }
    }
}
